const table_choices = [
  "zdecydownie tak",
  "tak",
  "trudno powiedzieć",
  "zdecydowanie nie",
  "nie",
];

const isReq = false;

export default [
  {
    type: "checkbox",
    name: "wiek",
    title: "wiek",
    isRequired: isReq,
    choices: ["> 18", "18-30", "30-40", "50 <"],
    maxSelectedChoices: 1
  },
  {
    type: "checkbox",
    name: "pleć",
    title: "pleć",
    choices: ["męzczyzna", "kobieta"],
    isRequired: isReq,
    maxSelectedChoices: 1
  },
  {
    type: "text",
    inputType: "number",
    name: "waga w kg",
    title: "podaj wage w kg",
    validators: [
        {
            type: "numeric",
            minValue: 20,
            maxValue: 200
        }
    ],
    isRequired: isReq,
  },
  {
    type: "text",
    inputType: "number",
    name: "wzrost w cm",
    title: "podaj wzrost w cm",
    isRequired: isReq,
  },
  {
    type: "checkbox",
    name: "zakres uprawniania sportu",
    title: "Zaznacz zakres w jakim uprawiasz sport",
    isRequired: isReq,
    choices: ["Rekreacynie", "Zawodowo"],
  },
  {
    type: "checkbox",
    name: "czas wysilku w ciagu dnia",
    title: "Ile przeciętnie trwa czas Twojego wysiłku fizycznego w ciągu dnia?",
    isRequired: isReq,
    choices: [
      "ponizej 15 minut",
      "15-30 minut",
      "ok 45 min",
      "godzinę",
      "więcej niz godzinę",
    ],
    maxSelectedChoices: 1,
  },
  {
    type: "checkbox",
    name: "rodzaj trenowanego sportu",
    title: "Jaki sport trenujesz? (zaznacz wszystkie pasujące)",
    choices: [
      "gry zespołowe",
      "akrobatyka/ gimnastyka",
      "podnoszenie ciężarów",
      "ekkoatletyka",
      "snowboard/narciarstwo",
      "kolarstwo",
      "biegi długodystansowe",
      "pływanie",
      "sporty walki",
      "taniec/fitness",
      "pięciobój nowoczesny",
    ],
    isRequired: isReq,
  },
  {
    type: "checkbox",
    name: "dlaczego stosuje post",
    title: "Dlaczego stosujesz post?",
    hasOther: true,
    otherText: "inny, podaj powód",
    choices: [
      "Aby schudnąć",
      "Dla wspomagania procesu autofagii",
      "apoptozy",
      "Zalecenia lekarza",
      "Dla oczyszczenia organizmu z toksyn",
      "Dla poprawy wyglądu",
      "Dla poprawy wyników sportowych",
      "dla satysfakcji osobistej",
      "Dla poprawy samopoczucia",
    ],
  },
  {
    type: "checkbox",
    name: "ilosc przebytych postow",
    title: "Ile razy stosowales post 24-72h ?",
    choices: [
      "1 raz",
      "mniej niż 5 razy",
      "mniej niż 10 razy",
      "mniej niż 20 razy",
      "więcej niż 20",
    ],
    maxSelectedChoices: 1,
  },
  {
    type: "radiogroup",
    name: "częstotliwosc uprawiania postow",
    title: "Czy regularnie stosujesz post?",
    choices: ["tak", "nie"],
    isRequired: isReq,
    hasToBeEdited: true,
  },
  {
    type: "dropdown",
    name: "odstep czasowy pomiedzy postami",
    title: "w jakich odstępach czasowych?",
    visibleIf: "{częstotliwosc uprawiania postow} ='tak'",
    choices: [
      "min co 2 tygodnie lub czesciej",
      "3-4 tygodnie",
      "1-3 miesiecy",
      "3-6 miesiecy",
      "6 miesiecy do 1 roku",
    ],
  },
  {
    type: "radiogroup",
    name: "czy byly robione badnia specjalistyczne przed i po poscie",
    title: "Czy przed i po poście badałeś się specjalistycznie? ",
    choices: ["tak", "nie"],
    isRequired: isReq,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na wynik badan specjalistycznych",
    title: "czy wyniki ulegly poprawie?",
    visibleIf:
      "{czy byly robione badnia specjalistyczne przed i po poscie} = 'tak'",
    choices: [
      "zdecydowanie tak",
      "tak",
      "trudno powiedziec",
      "zdcydowanie nie",
      "nie",
    ],
  },
  {
    type: "checkbox",
    name: "typ diety",
    title: "jaka diete stosujesz na codzien",
    choices: [
      "Dieta ketogeniczna",
      "Dieta meal replacement",
      "Dieta eliminacyjna",
      "Dieta białkowa",
      "Dieta monoskładnikowa",
      "Dieta zdrowotna",
      "Dieta Foot map",
      "Dieta paleo",
      "Dieta wysokotłuszczowa",
      "Dieta wegetariańska",
      "Dieta warzywno-owocowa",
      "Dieta autorska",
      "Dieta Wegańska",
      "nie zwracam uwagi na to co jem",
      "nie mam diety ale staram się  jeść racjonalnie",
    ],
    hasOther: true,
    otherText: "inna, podaj jaka",
    isRequired: isReq,
  },
  {
    type: "radiogroup",
    name: "Czy wczasie trwania postu podejmujesz aktywność fizyczna?",
    title: "Czy wczasie trwania postu podejmujesz aktywność fizyczna?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zmniejszenie aktywnosci fizycznej",
    title: "Czy po poście zmniejszasz ilość aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie aktywnosci fizycznej",
    title: "Czy po poście zwiększasz ilość aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie aktywnosci fizycznej",
    title: "Czy po poście zwiększasz ilość aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name:
      "wplyw postu na zwiekszenie czasu wykonywania cwiczen podczas aktywnosci fizycznej",
    title:
      "Czy po poście zwiększył się czas wykonywanych ćwiczeń podczas aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na odpornosc na zmeczenia podczas wysilku fizycznego",
    title:
      "Czy po poście czujesz się bardziej odporny na zmęczenie podczas wysiłku fizycznego?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na koncentracje podczas cwiczen",
    title: "Czy czujesz większą koncentrację podczas ćwiczeń?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie motywacji do cwiczen i uprawiania sportu",
    title:
      "Czy po poście zauważyłeś/aś większą motywację podczas aktywności fizycznej ?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na poprawe kondycji fizycznej",
    title: "Czy po poście czujesz poprawe kondycji fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie sily fizycznej",
    title: "Czy po poście czujesz zwiększenie siły fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie szybkosci i reakcji",
    title: "Czy po poście czujesz zwiększenie szybkości reakcji?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na gietkosc",
    title: "Czy po poście czujesz większą giętkość?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na wytrzymalosc fizyczna",
    title:
      "Czy po po poście czujesz zwiększenie wytrzymałości podczas ćwiczeń?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na latwosc budowania masy miesniowej",
    title: "Czy po poście łatwiej Ci jest budowac mase miesniowa?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na rozumienie wskazowek podczas wykonywania cwiczen",
    title:
      "Czy przyjmowane wskazówki podczas ćwiczeń są dla Ciebie bardziej klarowne/jasne?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na poczucie satysfakcji podczas wykonywania cwiczen",
    title:
      "Czy podczas ćwiczeń/po ćwiczeniach czujesz się bardziej szczęśliwy/ usatysfakcjonowany/ spełniony?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na utrzymywanie tkanki tluszczowej w ciele",
    title:
      "Czy po poście łatwiej Ci jest utrzymywać poziom tkanki tłuszczowej w ciele?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na reukcje tkanki tluszczowej w ciele",
    title: "Czy po poście łatwiej Ci jest zredukować tkankę tłuszczową?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na efekt jojo",
    title: "Czy po poście zauważyłeś/aś wzrost masy ciała — „efekt jojo”? ",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zmiane nawykow zywieniowych",
    title: "Czy po poście zmieniłeś/aś swoje nawyki żywieniowe?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na sen",
    title: "Czy Twój sen po poście jest spokojniejszy?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zapamietywanie",
    title: "Czy Twoja umiejętność zapamiętywania uległa poprawie?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na nastroj",
    title: "Czy Twój ogólny nastrój po poście uległ poprawie?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name:
      "wplyw postu na motywacje do podejmowania nowych wyzwan na rzecz ciala i umyslu",
    title:
      "Czy przebyty post motywuje Cię do podejmowania nowyh wyzwan na rzecz wlasnego ciala i umyslu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na decyzyjnosc i rozwiazywanie problemow",
    title:
      "Czy po poście czujesz latwosc podejmowania decyzji i lepiej rozwiazujesz problemy?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zmniejszenie problemow zdrowotnych",
    title:
      "Czy wszelkie problemy zdrowotne po poście zmniejszyły się lub ustały?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na metabolizm",
    title: "Czy po poście zauważyłeś/aś uregulowanie metabolizmu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na odczuwanie stresu i radzenie sobie z nim",
    title: "Czy po poście czujesz się odporniejszy na stres?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na stan umyslu",
    title: "Czy po poście czujesz spokój umysłu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na jakosc snu",
    title: "Czy po poście Twój sen jest lepszy?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "comment",
    name: "suggestions",
    title:
      "Jesli na temat postow masz wlasne spostrzezenia lub uwagi, ktorych nie uwzglednia ta ankieta i chcialbys sie nimi podzielic, mozesz to wpisac w polu ponizej",
  },
];
