const table_choices = [
  "zdecydownie tak",
  "tak",
  "trudno powiedzieć",
  "nie",
  "zdecydowanie nie",
];

const isReq = false;

export default [
  {
    type: "checkbox",
    name: "wiek",
    title: "wiek",
    isRequired: isReq,
    choices: ["> 18", "18-30", "30-40", "40 <"],
    maxSelectedChoices: 1
  },
  {
    type: "checkbox",
    name: "płeć",
    title: "płeć",
    choices: ["mężczyzna", "kobieta"],
    isRequired: isReq,
    maxSelectedChoices: 1
  },
  {
    type: "text",
    inputType: "number",
    name: "waga w kg",
    title: "Podaj wage w kg",
    validators: [
        {
            type: "numeric",
            minValue: 20,
            maxValue: 200
        }
    ],
    isRequired: isReq,
  },
  {
    type: "text",
    inputType: "number",
    name: "wzrost w cm",
    title: "Podaj wzrost w cm",
    isRequired: isReq,
  },
  {
    type: "checkbox",
    name: "zakres uprawniania sportu",
    title: "Zaznacz zakres w jakim uprawiasz sport",
    isRequired: isReq,
    choices: ["Rekreacyjnie", "Zawodowo"],
  },
  {
    type: "checkbox",
    name: "czas wysilku w ciagu dnia",
    title: "Ile przeciętnie trwa czas Twojego wysiłku fizycznego w ciągu dnia?", 
    isRequired: isReq,
    choices: [
      "ponizej 15 minut",
      "15-30 minut",
      "ok 45 min",
      "godzinę",
      "więcej niż godzinę",
    ],
    maxSelectedChoices: 1,
  },
  {
    type: "checkbox",
    name: "rodzaj trenowanego sportu",
    title: "Jaki sport trenujesz? (zaznacz wszystkie pasujące)",
    choices: [
      "gry zespołowe",
      "akrobatyka/ gimnastyka",
      "podnoszenie ciężarów",
      "lekkoatletyka",
      "snowboard/narciarstwo",
      "kolarstwo/jazda na rowerze",
      "biegi długodystansowe",
      "biegi sprinterskie",
      "pływanie",
      "sporty walki",
      "taniec/fitness",
      "pięciobój nowoczesny",
      "kulturystyka/sporty sylwetkowe",
      "crossfit/kalistenika",
    ],
    isRequired: isReq,
  },
  {
    type: "checkbox",
    name: "dlaczego stosuje post",
    title: "Dlaczego stosujesz post? (zaznacz wszystkie pasujące)",
    hasOther: true,
    otherText: "inny, podaj powód",
    choices: [
      "Aby schudnąć",
      "Dla zdrowia",
      "Aby wywołać proces autofagii, apoptozy",
      "Ze względów religijnych",
      "Zalecenie lekarza",
      "Dla oczyszczenia organizmu z toksyn",
      "Dla poprawy wyglądu",
      "Dla poprawy wyników sportowych",
      "Dla satysfakcji osobistej",
      "Dla poprawy samopoczucia",
      "Dla efektu lekkości w układzie trawiennym"
    ],
  },
  {
    type: "checkbox",
    name: "ilosc przebytych postow",
    title: "Ile razy stosowałeś post trwający 72h?",
    choices: [
      "1 raz",
      "mniej niż 5 razy",
      "mniej niż 10 razy",
      "mniej niż 20 razy",
      "więcej niż 20",
    ],
    maxSelectedChoices: 1,
  },
  {
    type: "radiogroup",
    name: "częstotliwość uprawiania postow",
    title: "Czy regularnie stosujesz post?",
    choices: ["tak", "nie"],
    isRequired: isReq,
    hasToBeEdited: true,
  },
  {
    type: "dropdown",
    name: "odstep czasowy pomiedzy postami",
    title: "W jakich odstępach czasowych?",
    visibleIf: "{częstotliwosc uprawiania postow} ='tak'",
    choices: [
      "minimum co 2 tygodnie lub częściej",
      "3-4 tygodnie",
      "1-3 miesiące",
      "3-6 miesiące",
      "od pół roku do 1 roku",
    ],
  },
  {
    type: "radiogroup",
    name: "czy byly robione badnia specjalistyczne przed i po poscie",
    title: "Czy przed i po poście badałeś się specjalistycznie? ",
    choices: ["tak", "nie"],
    isRequired: isReq,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na wynik badan specjalistycznych",
    title: "Czy wyniki po poście ulegly poprawie?",
    visibleIf:
      "{czy byly robione badnia specjalistyczne przed i po poscie} = 'tak'",
    choices: [
      "zdecydowanie tak",
      "tak",
      "trudno powiedziec",
      "nie",
      "zdecydowanie nie",
    ],
  },
  {
    type: "checkbox",
    name: "typ diety",
    title: "Jaką dietę stosujesz na codzień?",
    choices: [
      "Dieta ketogeniczna",
      "Dieta meal replacement",
      "Dieta eliminacyjna",
      "Dieta białkowa",
      "Dieta monoskładnikowa",
      "Dieta zdrowotna",
      "Dieta Foot map",
      "Dieta Paleo",
      "Dieta wysokotłuszczowa",
      "Dieta wegetariańska",
      "Dieta warzywno-owocowa",
      "Dieta autorska",
      "Dieta Wegańska",
      "Nie zwracam uwagi na to co jem",
      "Nie mam diety ale staram się jeść racjonalnie",
    ],
    hasOther: true,
    otherText: "inna, podaj jaka",
    isRequired: isReq,
  },
  {
    type: "radiogroup",
    name: "Czy wczasie trwania postu podejmujesz aktywność fizyczna?",
    title: "Czy w czasie trwania postu podejmujesz aktywność fizyczną?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zmniejszenie aktywnosci fizycznej",
    title: "Czy po poście zmniejszasz ilość aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie aktywnosci fizycznej",
    title: "Czy po poście zwiększasz ilość aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie aktywnosci fizycznej",
    title: "Czy ?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name:
      "wplyw postu na zwiekszenie czasu wykonywania cwiczen podczas aktywnosci fizycznej",
    title:
      "Czy po poście zwiększył się czas/liczba powtórzeń wykonywanych ćwiczeń podczas sesji treningowej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na odpornosc na zmeczenia podczas wysilku fizycznego",
    title:
      "Czy po poście czujesz się bardziej odporny na zmęczenie podczas sesji treningowej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na koncentracje podczas cwiczen",
    title: "Czy po poście czujesz większą koncentrację podczas ćwiczeń?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie motywacji do cwiczen i uprawiania sportu",
    title:
      "Czy po poście zauważyłeś/aś większą motywację podczas aktywności fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na wyniki sportowe",
    title: "Czy po poście zauważyłeś/aś poprawę osiąganych wyników sportowych?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na poprawe kondycji fizycznej",
    title: "Czy po poście czujesz poprawe kondycji fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie sily fizycznej",
    title: "Czy po poście czujesz zwiększenie siły fizycznej?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zwiekszenie szybkosci i reakcji",
    title: "Czy po poście czujesz zwiększenie szybkości reakcji?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na gietkosc",
    title: "Czy po poście czujesz większą gibkość?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na wytrzymalosc fizyczna",
    title:
      "Czy po po poście czujesz zwiększenie wytrzymałości swojego organizmu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wpływ postu na latwosc budowania masy miesniowej",
    title: "Czy po poście łatwiej Ci jest budować masę mieśniową?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wpływ postu na rozumienie wskazowek podczas wykonywania cwiczen",
    title:
      "Czy wskazówki/polecenia podczas ćwiczeń są dla Ciebie bardziej klarowne/jasne?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na poczucie satysfakcji podczas wykonywania cwiczen",
    title:
      "Czy podczas ćwiczeń/po ćwiczeniach czujesz się bardziej szczęśliwy/ usatysfakcjonowany/spełniony?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na utrzymywanie tkanki tluszczowej w ciele",
    title:
      "Czy po poście łatwiej Ci jest utrzymywać poziom tkanki tłuszczowej w ciele?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na reukcje tkanki tluszczowej w ciele",
    title: "Czy po poście łatwiej Ci jest zredukować tkankę tłuszczową?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na efekt jojo",
    title: "Czy po poście zauważyłeś/aś wzrost masy ciała — „efekt jojo”?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zmiane nawykow zywieniowych",
    title: "Czy po poście zmieniłeś/aś swoje nawyki żywieniowe?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na puls i cisnienie krwi",
    title: "Czy zauważyłeś/aś poprawę w wynikach ciśnienia krwi i pulsu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na stan umyslu",
    title: "Czy po poście czujesz się pewniejszy siebie?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na zapamietywanie",
    title: "Czy Twoja umiejętność zapamiętywania i koncentracji uległa poprawie?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na decyzyjnosc i rozwiazywanie problemow",
    title:
      "Czy po poście czujesz łatwość podejmowania decyzji, rozwiązywania problemów i lepszą kontrole emocji?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na nastroj",
    title: "Czy Twój ogólny nastrój po poście uległ poprawie?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na odczuwanie stresu i radzenie sobie z nim",
    title: "Czy po poście czujesz się odporniejszy na stres?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name:
      "wplyw postu na motywacje do podejmowania nowych wyzwan na rzecz ciala i umyslu",
    title:
      "Czy przebyty post motywuje Cię do podejmowania nowych wyzwań na rzecz własnego ciała i umysłu?",
    isRequired: isReq,
    choices: table_choices,
  },

  {
    type: "radiogroup",
    name: "wplyw postu na zmniejszenie problemow zdrowotnych",
    title:
      "Czy wszelkie problemy zdrowotne po poście zmniejszyły się lub ustały?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na metabolizm",
    title: "Czy po poście zauważyłeś/aś uregulowanie metabolizmu?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "radiogroup",
    name: "wplyw postu na jakosc snu",
    title: "Czy po poście Twój sen jest lepszy?",
    isRequired: isReq,
    choices: table_choices,
  },
  {
    type: "comment",
    name: "suggestions",
    title:
      "Jeżeli na temat postów masz własne spostrzeżenia lub uwagi, których nie uwzglednia ta ankieta i możesz się z nimi podzielić, wpisz je w polu poniżej",
  },
];
